package observer;

public enum Evento {
    JUGADOR_AGREGADO,
    PARTIDA_INICIADA,
    DADOS_TIRADOS,
    DADOS_SELECCIONADOS,
    TURNO_PERDIDO,
    JUGADOR_PLANTADO,
    CAMBIO_TURNO,
    PARTIDA_FINALIZADA,
    PARTIDA_CARGADA
}
